FROM python:3.11-slim

WORKDIR /app

COPY requirements-api.txt . 

RUN pip install --no-cache-dir -r requirements-api.txt

COPY app ./app
COPY attack_pipeline.joblib severity_pipeline.joblib type_random_forest.pkl ./

EXPOSE 8000

CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]